### ISSUE TITLE
Minor issue on line 21 udp_server.py

### ISSUE THREAD

**Issue by i7az** [dwoz/python-nat-hole-punching#4]
line 21 duplicated from line 19
```logger.info("server - send client info to: %s", addresses[0])```
should be
```logger.info("server - send client info to: %s", addresses[1])```

**Comment by dwoz** [comment]
@iTazGoGo Thanks, Mind making a PR for this?

**Comment by iTazGoGo** [comment]
got bored

**Comment by i7az** [comment]
there you go

**Comment by dwoz** [comment]
Yep, PR merged. Thanks!
