### ISSUE TITLE
why 1_accept bind on client public address port

### ISSUE THREAD

**Issue by gufengxiaoyuehan** [dwoz/python-nat-hole-punching#5]
thanks for your contributions, but one thing I can understands is why bind client_pub_add in tcp_client line 75, thanks for your reply.

    threads = {
        "0_accept": Thread(target=accept, args=(priv_addr[1], )),
        "1_accept": Thread(target=accept, args=(client_pub_addr[1], )), -- this line
        "2_connect": Thread(target=connect, args=(priv_addr, client_pub_addr,)),
        "3_connect": Thread(target=connect, args=(priv_addr, client_priv_addr)),
    }

**Comment by abhi204** [comment]
I think the author accidentally wrote client_pub_addr instead of **pub_addr**.

**Comment by gufengxiaoyuehan** [comment]
@abhi204 never mind  :./

**Comment by reza3320** [comment]
> @abhi204 never mind :./

Could you use the code?
did it run properly and did the clients connect to each other??
I'm trying to use it but the clients sent syn to each other but they are not answering that with syn-ack
I don't know do they receive it or they are not responding.
